export const hradecEvents = [
  {
    title: "Hradec – Tech Meetup",
    description: "Monthly tech meetup for developers.",
    lat: 50.2093,
    lng: 15.8326,
    dayOffset: 2,
    hourOffset: 18,
    minuteOffset: 30,
  },
  {
    title: "Outdoor Workout",
    description: "Public calisthenics training.",
    lat: 50.2191,
    lng: 15.825,
    dayOffset: 4,
    hourOffset: 9,
    minuteOffset: 0,
  },
  {
    title: "Salsa Night",
    description: "Dance event for beginners.",
    lat: 50.2099,
    lng: 15.8455,
    dayOffset: 6,
    hourOffset: 20,
    minuteOffset: 15,
  },
  {
    title: "Board Games Evening",
    description: "Casual board games meetup for all ages.",
    lat: 50.2121,
    lng: 15.8329,
    dayOffset: 1,
    hourOffset: 17,
    minuteOffset: 45,
  },
  {
    title: "Karaoke Night",
    description: "Sing your heart out and have fun.",
    lat: 50.2108,
    lng: 15.8291,
    dayOffset: 5,
    hourOffset: 21,
    minuteOffset: 0,
  },
  {
    title: "Coffee & Code",
    description: "Coworking and coding session for devs.",
    lat: 50.2175,
    lng: 15.8322,
    dayOffset: 3,
    hourOffset: 10,
    minuteOffset: 15,
  },
  {
    title: "Running Club Meetup",
    description: "5km run around Šimkovy sady.",
    lat: 50.2097,
    lng: 15.8234,
    dayOffset: 2,
    hourOffset: 7,
    minuteOffset: 0,
  },
  {
    title: "Photography Walk",
    description: "Urban photo shooting around the old town.",
    lat: 50.2149,
    lng: 15.8337,
    dayOffset: 7,
    hourOffset: 16,
    minuteOffset: 20,
  },
  {
    title: "Open Mic Standup",
    description: "Try your jokes on stage!",
    lat: 50.2112,
    lng: 15.8359,
    dayOffset: 6,
    hourOffset: 19,
    minuteOffset: 30,
  },
  {
    title: "Plant Swap Meetup",
    description: "Bring a plant, take a plant.",
    lat: 50.2103,
    lng: 15.8345,
    dayOffset: 4,
    hourOffset: 14,
    minuteOffset: 0,
  },
  {
    title: "Chess in the Park",
    description: "Casual chess meetups in Šimkovy sady.",
    lat: 50.21,
    lng: 15.826,
    dayOffset: 1,
    hourOffset: 15,
    minuteOffset: 30,
  },
  {
    title: "VR Gaming Session",
    description: "Try VR games together.",
    lat: 50.2087,
    lng: 15.8312,
    dayOffset: 5,
    hourOffset: 18,
    minuteOffset: 10,
  },
  {
    title: "Outdoor Movie Night",
    description: "Open-air screening with blankets and snacks.",
    lat: 50.2055,
    lng: 15.8277,
    dayOffset: 7,
    hourOffset: 20,
    minuteOffset: 45,
  },
  {
    title: "Bouldering Session",
    description: "Climbing meetup for beginners.",
    lat: 50.2233,
    lng: 15.8399,
    dayOffset: 3,
    hourOffset: 18,
    minuteOffset: 0,
  },
  {
    title: "Yoga by the River",
    description: "Relaxing yoga session near Labe.",
    lat: 50.2131,
    lng: 15.8298,
    dayOffset: 2,
    hourOffset: 8,
    minuteOffset: 0,
  },
  {
    title: "D&D Adventure Night",
    description: "One-shot campaign for beginners.",
    lat: 50.2117,
    lng: 15.8349,
    dayOffset: 5,
    hourOffset: 17,
    minuteOffset: 30,
  },
  {
    title: "Live Jazz Evening",
    description: "Smooth jazz in a local pub.",
    lat: 50.209,
    lng: 15.8335,
    dayOffset: 6,
    hourOffset: 20,
    minuteOffset: 0,
  },
  {
    title: "Dog Owners Meetup",
    description: "Friendly walk around the park.",
    lat: 50.2125,
    lng: 15.8294,
    dayOffset: 3,
    hourOffset: 11,
    minuteOffset: 30,
  },
  {
    title: "Painting Session",
    description: "Bring your art supplies and paint together.",
    lat: 50.2143,
    lng: 15.832,
    dayOffset: 1,
    hourOffset: 16,
    minuteOffset: 45,
  },
  {
    title: "Coding Interview Practice",
    description: "Mock interviews and algorithm practice.",
    lat: 50.2105,
    lng: 15.8371,
    dayOffset: 4,
    hourOffset: 18,
    minuteOffset: 0,
  },
];
